In [1]:
import torch

In [2]:
a = torch.FloatTensor(2,3)
b = torch.FloatTensor([3,4,5,7])
print(a)
print(b)
print(type(a))
print(b.dtype)
print(b.size())

tensor([[ 0.0000e+00, -1.5846e+29,  0.0000e+00],
        [-1.5846e+29,  2.3168e+04,  4.5908e-41]])
tensor([3., 4., 5., 7.])
<class 'torch.Tensor'>
torch.float32
torch.Size([4])


float32\float64(double已经被新版本取消了）

In [3]:
a = torch.IntTensor(2,3)
b = torch.IntTensor([3,4,5,7])
print(a)
print(b)
print(type(a))
print(b.dtype)
print(b.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([3, 4, 5, 7], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
torch.Size([4])


这个是生成int型tensor

In [4]:
a = torch.rand(2,3)
print(a)
print(type(a))
print(a.dtype)

tensor([[0.8521, 0.5316, 0.0618],
        [0.6139, 0.0399, 0.7142]])
<class 'torch.Tensor'>
torch.float32


这个部分是服从0-1的均匀分布

In [5]:
a = torch.randn(2,3)
print(a)
print(type(a))
print(a.dtype)

tensor([[ 0.8018, -0.5918,  0.0641],
        [ 0.5202,  0.3213,  0.2316]])
<class 'torch.Tensor'>
torch.float32


 随机生成的浮点数的取值满 均值为0、方差为1的正态分布。

In [6]:
a = torch.randn(2,3)
print(a)
print(type(a))
print(a.dtype)

tensor([[-0.7302,  0.1805,  0.2081],
        [ 0.2082,  1.4065,  0.2813]])
<class 'torch.Tensor'>
torch.float32


In [7]:
#mean为张  std为张 
mean = torch.arange(1,6,dtype=torch.float)
std = torch.arange(1,6,dtype=torch.float)
t = torch.normal(mean,std)
print(mean)
print(type(mean))
print(mean.dtype)
print(std)
print(type(std))
print(std.dtype)
print(t)

tensor([1., 2., 3., 4., 5.])
<class 'torch.Tensor'>
torch.float32
tensor([1., 2., 3., 4., 5.])
<class 'torch.Tensor'>
torch.float32
tensor([ 1.6848, -1.4714,  9.5572,  1.3403,  4.6049])


mean和std是张量，生成规则是mean1，std1的正态分布采样；mean2，std2 balabala

In [8]:
#mean为标  std为标 
t = torch.normal(0.2,1.0,size=(5,))
print(t)

tensor([ 0.1511,  0.2069, -1.7728, -1.5113, -0.2910])


In [9]:
#mean为标  std为张 
mean = 2
std = torch.arange(1,4,dtype=torch.float)
t = torch.normal(mean,std)
print("mean:{},std:{}".format(mean,std))
print(t)

mean:2,std:tensor([1., 2., 3.])
tensor([ 2.0666, -1.9278, -1.2204])


In [10]:
#mean为张  std为标 
mean = torch.arange(1,4,dtype=torch.float)
std = 2
t = torch.normal(mean,std)
print("mean:{},std:{}".format(mean,std))
print(t)

mean:tensor([1., 2., 3.]),std:2
tensor([0.5247, 0.8697, 5.0507])


In [11]:
a = torch.range(1,5,1)
b = torch.arange(1,5,1)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

tensor([1., 2., 3., 4., 5.])
torch.float32
tensor([1, 2, 3, 4])
torch.int64


<ipython-input-11-59e56a4df551>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(1,5,1)


range好像不让用了，生成的type也不一样

In [12]:
a=torch.ones(2,5)
b=torch.randn_like(a)
c=torch.zeros(2,5)
print(a)
print(b)
print(c)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 1.0675,  3.4921, -2.3565, -0.1579, -0.4538],
        [-1.2986, -0.3241, -1.7721, -0.8157, -1.0444]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


# 总结
前面这段学了pytorch的生成机制
+ 生成机制
    - 可以通过FloatTensor（2,3）生成指定形状，数据类型，但是数据随机的张量
    - 可以通过FloatTensor（【2,3,4，5】）生成指定内容的张量
    - 可以通过rand和randn（2,5）生成形状指定，数据服从均匀、正态分布的张量
    - 可以通过range（1,5,1）生成指定步长和起始终止的float一维张量（包含5）
    - 可以通过arange（1,5,1）生成int张量（不包含5）
    - 可以通过ones/zeros生成指定形状的1,0矩阵
    - 可以通过randn_like生成和某张量大小类似的张量（逻辑上好看些）

In [13]:
a = torch.randn(2,3)
print(a)
b = torch.abs(a)
print(b)

tensor([[ 1.0090, -0.3117, -0.3332],
        [ 0.7601, -0.4121,  0.6323]])
tensor([[1.0090, 0.3117, 0.3332],
        [0.7601, 0.4121, 0.6323]])


In [14]:
a = torch.randn(2,3)
print(a)
b = torch.randn(2,3)
print(b)
c = torch.add(a,b)
print(c)
print(a.add(b))
print("a.add后的a值 ",a)
print(a.add_(b))
print("a.add_后的a值 ",a)
d = torch.randn(2,3)
print(d)
e = torch.add(d,10)
print(e)

tensor([[ 0.4166, -1.1137, -0.1583],
        [-1.6606, -0.2080, -0.9639]])
tensor([[-1.6722,  0.0184, -0.8000],
        [-0.9226, -0.7697, -1.2405]])
tensor([[-1.2556, -1.0953, -0.9583],
        [-2.5832, -0.9777, -2.2044]])
tensor([[-1.2556, -1.0953, -0.9583],
        [-2.5832, -0.9777, -2.2044]])
a.add后的a值  tensor([[ 0.4166, -1.1137, -0.1583],
        [-1.6606, -0.2080, -0.9639]])
tensor([[-1.2556, -1.0953, -0.9583],
        [-2.5832, -0.9777, -2.2044]])
a.add_后的a值  tensor([[-1.2556, -1.0953, -0.9583],
        [-2.5832, -0.9777, -2.2044]])
tensor([[-0.2627,  0.5623, -0.3668],
        [ 0.9965,  1.6342, -1.3331]])
tensor([[ 9.7373, 10.5623,  9.6332],
        [10.9965, 11.6342,  8.6669]])


所有对于原张量进行改动的都要加上_

In [15]:
a = torch.randn(2,3)
print(a)
b = torch.clamp(a, -0.1, 0.1)
print(b)

tensor([[-0.5743,  0.6774,  1.0702],
        [ 1.2786, -1.6769,  0.6661]])
tensor([[-0.1000,  0.1000,  0.1000],
        [ 0.1000, -0.1000,  0.1000]])


In [16]:
a = torch.randn(2,3)
print(a)
b = torch.randn(2,3)
print(b)
c = torch.div(a,b)
print(c)
d = torch.randn(2,3)
print(d)
e = torch.div(d, 10)
print(e)

tensor([[-1.2776, -0.6916,  2.4188],
        [ 0.8735, -1.3093, -2.1834]])
tensor([[-0.5290,  0.2988,  1.2027],
        [-0.2817, -1.0404,  0.5863]])
tensor([[ 2.4153, -2.3149,  2.0111],
        [-3.1015,  1.2585, -3.7239]])
tensor([[-1.3122, -1.1534,  0.6019],
        [-1.1550, -0.6156,  0.2867]])
tensor([[-0.1312, -0.1153,  0.0602],
        [-0.1155, -0.0616,  0.0287]])


In [17]:
a = torch.rand(2,3)
print(a)
b = torch.rand(2,3)
print(b)
c = torch.mul(a,b)
print(c)
d = torch.randn(2,3)
print(d)
e = torch.mul(d, 10)
print(e)

tensor([[0.6783, 0.5456, 0.7342],
        [0.7695, 0.7927, 0.3905]])
tensor([[0.7687, 0.6713, 0.9451],
        [0.8055, 0.2721, 0.0520]])
tensor([[0.5215, 0.3662, 0.6939],
        [0.6198, 0.2157, 0.0203]])
tensor([[ 1.8437, -0.2861, -0.3771],
        [-0.3717, -0.0838, -0.0642]])
tensor([[18.4369, -2.8614, -3.7713],
        [-3.7166, -0.8381, -0.6418]])


In [18]:
a = torch.randn(2,3)
print(a)
b = torch.pow(a,2)
print(b)

tensor([[-0.0916, -1.9133,  0.8955],
        [-0.2680, -0.3965,  0.2904]])
tensor([[0.0084, 3.6608, 0.8020],
        [0.0718, 0.1572, 0.0843]])


注意mul和div、pow都是对位运算，不是矩阵运算。

In [19]:
a = torch.randn(2,3)
print(a)
b = torch.randn(3,2)
print(b)
c = torch.mm(a,b)
print(c)

tensor([[ 0.3416,  0.2638,  0.7572],
        [-0.2134, -1.2006, -0.3186]])
tensor([[-0.8635,  1.2733],
        [-0.5113,  0.1311],
        [ 0.3946,  1.5734]])
tensor([[-0.1311,  1.6610],
        [ 0.6725, -0.9304]])


这个才是矩阵运算

In [20]:
a = torch.randn(2,3)
print(a)
b = torch.randn(3)
print(b)
c = torch.mv(a,b)
print(c)

tensor([[ 1.2984, -1.2511,  1.1866],
        [-0.9507,  0.9329, -0.0231]])
tensor([-0.8250,  0.8170,  0.4355])
tensor([-1.5766,  1.5365])


这个是矩阵和向量乘，matrix vector

# 总结
这一部分讲了矩阵的运算
+ 乘法总结
    - abs(a)用来搞绝对值
    - b = torch.clamp(a, -0.1, 0.1)用来剪切，可以用来实现relu
    - c = torch.div(a,b)对位相乘
    - c = torch.div(a,b)对位相除
    - b = torch.pow(a,2)每个平方
    - c = torch.mm(a,b)矩阵乘法
    - c = torch.mv(a,b)矩阵乘向量

In [21]:
a_tensor = torch.rand(3,4)
a_tensor.shape

torch.Size([3, 4])

In [22]:
a_tensor.size()

torch.Size([3, 4])

In [23]:
a_tensor.numel()

12

In [24]:
a_tensor.reshape(2,6)

tensor([[0.8398, 0.8531, 0.4312, 0.9303, 0.0077, 0.7480],
        [0.4492, 0.1241, 0.1130, 0.4367, 0.3984, 0.8872]])

In [25]:
multi_data=torch.ones(1,2,3,1,5)
multi_data.size()

torch.Size([1, 2, 3, 1, 5])

In [26]:
multi_data_temp=torch.squeeze(multi_data)
multi_data_temp.size()

torch.Size([2, 3, 5])

上面这个地方没太搞懂，再来测试一下

In [27]:
m=torch.ones(1,2)
m=torch.ones(2,2)
m

tensor([[1., 1.],
        [1., 1.]])

看懂了，所以上面那个（1，2，3，1，5）是一个五维的张量，规定了每一维的数据
那么squeeze就是从所有维度中剔除size 1的维度。
这个squeeze会直接改变张量的大小，内容，不用像运算里面那样加上_才可以

In [28]:
multi_data_temp = torch.squeeze(multi_data,0)
multi_data_temp.size()

torch.Size([2, 3, 1, 5])

他有一个dim参数，可以指定移出哪一个维度，如果size不为1那么不发生改变

In [29]:
multi_data = torch.ones(3,4)
multi_data

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
multi_data_temp = torch.unsqueeze(multi_data,1)
multi_data_temp.size()

torch.Size([3, 1, 4])

In [31]:
multi_data_temp = torch.unsqueeze(multi_data,-1)
multi_data_temp.size()

torch.Size([3, 4, 1])

有了squeeze当然也可以unsqueeze

In [32]:
a_tensor = torch.arange(4).reshape(1,4)
a_tensor

tensor([[0, 1, 2, 3]])

In [33]:
a_tensor.shape

torch.Size([1, 4])

In [34]:
b_tensor=a_tensor.expand(3,4)
b_tensor.shape

torch.Size([3, 4])

    size是有()的方法，shape是tensor的属性不用加（）
    expand在维数为1的维度上 行拓展 其他维度保持与原来一样即可,可以先使用.size()查看原始维度 如果没有维数为1的维度则不 拓展 

In [35]:
b_tensor

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])

In [36]:
a_tensor=a_tensor.reshape(4,1)
a_tensor

tensor([[0],
        [1],
        [2],
        [3]])

In [37]:
b_tensor=a_tensor.expand(4,2)
b_tensor

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

torch.repeat()  根据指定的维度进行填充 指定的值为扩展的倍数 指定的维数不少于原始维数 但可以增加维数以增加新维度

In [38]:
a = torch.arange(4).reshape(2,2)
print(a)
b = a.repeat(1,2)
print(b)
c = a.repeat(2,2)
print(c)
d = a.repeat(1,2,3)
print(d)

tensor([[0, 1],
        [2, 3]])
tensor([[0, 1, 0, 1],
        [2, 3, 2, 3]])
tensor([[0, 1, 0, 1],
        [2, 3, 2, 3],
        [0, 1, 0, 1],
        [2, 3, 2, 3]])
tensor([[[0, 1, 0, 1, 0, 1],
         [2, 3, 2, 3, 2, 3],
         [0, 1, 0, 1, 0, 1],
         [2, 3, 2, 3, 2, 3]]])


torch.cat()  将所给tensor按照指定维度拼接。这个dim还是对于维度进行指定。

In [39]:
a_tensor = torch.rand(2,3)
print(a_tensor)
b_tensor = torch.cat((a_tensor,a_tensor), dim = 0)
print(b_tensor)
c_tensor = torch.cat((a_tensor,a_tensor), dim = 1)
print(c_tensor)

tensor([[0.9891, 0.3842, 0.6609],
        [0.2209, 0.5084, 0.5876]])
tensor([[0.9891, 0.3842, 0.6609],
        [0.2209, 0.5084, 0.5876],
        [0.9891, 0.3842, 0.6609],
        [0.2209, 0.5084, 0.5876]])
tensor([[0.9891, 0.3842, 0.6609, 0.9891, 0.3842, 0.6609],
        [0.2209, 0.5084, 0.5876, 0.2209, 0.5084, 0.5876]])


In [40]:
a_tensor = torch.rand(2,3)
print(a_tensor)
print(a_tensor.shape)
b_tensor = torch.stack((a_tensor,a_tensor), dim = 0)
print(b_tensor)
print(b_tensor.shape)
c_tensor = torch.stack((a_tensor,a_tensor), dim = 1)
print(c_tensor)
print(c_tensor.shape)
d_tensor = torch.stack((a_tensor,a_tensor), dim = 2)
print(d_tensor)
print(d_tensor.shape)

tensor([[0.1962, 0.6870, 0.2754],
        [0.6375, 0.4121, 0.1425]])
torch.Size([2, 3])
tensor([[[0.1962, 0.6870, 0.2754],
         [0.6375, 0.4121, 0.1425]],

        [[0.1962, 0.6870, 0.2754],
         [0.6375, 0.4121, 0.1425]]])
torch.Size([2, 2, 3])
tensor([[[0.1962, 0.6870, 0.2754],
         [0.1962, 0.6870, 0.2754]],

        [[0.6375, 0.4121, 0.1425],
         [0.6375, 0.4121, 0.1425]]])
torch.Size([2, 2, 3])
tensor([[[0.1962, 0.1962],
         [0.6870, 0.6870],
         [0.2754, 0.2754]],

        [[0.6375, 0.6375],
         [0.4121, 0.4121],
         [0.1425, 0.1425]]])
torch.Size([2, 3, 2])


    这个拼接的过程：https://blog.csdn.net/qq_39709535/article/details/80803003?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522164739634716781685322584%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=164739634716781685322584&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_positive~default-1-80803003.142^v2^control,143^v4^control&utm_term=torch.cat&spm=1018.2226.3001.4187
    
    torch.column_stack 同torch.hstack 、torch.row_stack （同torch.vstack） 可分别对列和行角度拼接 是一般拼接操作的细化
    
    能够进行平移当然也能进行分割，用torch.chunk进行处理，返回的是一个张量元祖

In [41]:
a_tensor = torch.rand(4,4)
print(a_tensor)
b_tensor = torch.chunk(a_tensor, 2, dim=0)
print(b_tensor)
c_tensor = torch.chunk(a_tensor, 2, dim=1)
print(c_tensor)

tensor([[0.6626, 0.0549, 0.1099, 0.7250],
        [0.9665, 0.8746, 0.2710, 0.5915],
        [0.1601, 0.9390, 0.9620, 0.5720],
        [0.8252, 0.3096, 0.0801, 0.8363]])
(tensor([[0.6626, 0.0549, 0.1099, 0.7250],
        [0.9665, 0.8746, 0.2710, 0.5915]]), tensor([[0.1601, 0.9390, 0.9620, 0.5720],
        [0.8252, 0.3096, 0.0801, 0.8363]]))
(tensor([[0.6626, 0.0549],
        [0.9665, 0.8746],
        [0.1601, 0.9390],
        [0.8252, 0.3096]]), tensor([[0.1099, 0.7250],
        [0.2710, 0.5915],
        [0.9620, 0.5720],
        [0.0801, 0.8363]]))


torch.split()  将tensor按指定维度划分 可通过list指定划分的块大小。

In [42]:
a_tensor = torch.rand(4,4)
print(a_tensor)
b_tensor = torch.split(a_tensor, 2, dim=0)
print(b_tensor)
c_tensor = torch.split(a_tensor, [3,1], dim=0)
print(c_tensor)
d_tensor = torch.split(a_tensor, [1,3], dim=1)
print(d_tensor)

tensor([[0.7181, 0.9808, 0.2986, 0.4026],
        [0.2820, 0.6069, 0.0490, 0.3525],
        [0.6960, 0.0921, 0.9289, 0.8230],
        [0.7128, 0.5931, 0.2625, 0.6398]])
(tensor([[0.7181, 0.9808, 0.2986, 0.4026],
        [0.2820, 0.6069, 0.0490, 0.3525]]), tensor([[0.6960, 0.0921, 0.9289, 0.8230],
        [0.7128, 0.5931, 0.2625, 0.6398]]))
(tensor([[0.7181, 0.9808, 0.2986, 0.4026],
        [0.2820, 0.6069, 0.0490, 0.3525],
        [0.6960, 0.0921, 0.9289, 0.8230]]), tensor([[0.7128, 0.5931, 0.2625, 0.6398]]))
(tensor([[0.7181],
        [0.2820],
        [0.6960],
        [0.7128]]), tensor([[0.9808, 0.2986, 0.4026],
        [0.6069, 0.0490, 0.3525],
        [0.0921, 0.9289, 0.8230],
        [0.5931, 0.2625, 0.6398]]))


# 总结
这一部分讲拼接和分割，还是挺好玩的。但是要对dim和分割的方法非常熟悉，各个维度怎么操作的要清晰。
+ 拼接分割
     - squeeze干掉维度1的
     - unsqueeze在指定维度插入size1的新维度的新张量
     - expand拓展维度size1的
     - repeat填充，参数是行重复次数，列重复次数，新维度重复次数
     - cat拼接
     - stack在新维度上进行拼接
     - chunk分割成不同张量
     - split不仅可以分割还可以指定分割大小
       

In [43]:
a_tensor = torch.ones(5)
b_np = a_tensor.numpy()
print(type(a_tensor),type(b_np))
print(a_tensor, b_np)
a_tensor += 1
print(a_tensor, b_np)
b_np += 1
print(a_tensor, b_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


说明通过numpy生成的是会跟随一起改变的，他们共享相同的内存

In [44]:
c_tensor = torch.from_numpy(b_np)
print(type(c_tensor),type(b_np))
print(b_np, c_tensor)
b_np += 1
print(b_np, c_tensor)
c_tensor += 1
print(b_np, c_tensor)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.])
[4. 4. 4. 4. 4.] tensor([4., 4., 4., 4., 4.])
[5. 5. 5. 5. 5.] tensor([5., 5., 5., 5., 5.])


In [45]:
import numpy as np
a_np = np.ones(5)
b_tensor = torch.from_numpy(a_np)
print(a_np, b_tensor)
a_np += 1
print(a_np, b_tensor)
b_tensor += 1
print(a_np, b_tensor)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [46]:
a_np = np.ones(5)
c_tensor = torch.tensor(a_np)
a_np += 1
print(a_np, c_tensor)

[2. 2. 2. 2. 2.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# 总结
pytorch的tensor和numpy共用一个内存，转换很快。但如果使用torch.tensor将numpy数组转换成tensor，该方法会进行数据拷贝，返回的tensor和原来数据不共享内存。

好了，你已经学会pytorch了，下面开始科研吧（bushi）先搭建一个简单的神经网络试试看。

In [47]:
import torch
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

单层神经网络，一批次输入100个数据，input_data每个数据包含特征1000，hidden-layer定义经过隐藏层后保留的数据特征个数。output_layer输出的数据，最后需要10分类。

一个批次的数据从输入到输出的完整过程是：先输入100个具有1000个特征的数据 经隐藏层后变成100个具
有100个特征的数据 再经过输出层后输出100个具有10个分类结果值的数据 在得到输出结果之后计算损失并
进行后向传播 这样一次模型的训练就完成了 然后循环整个流程就可以完成指定次数的训练 并达到优化模型
参数的目的。

In [48]:
#准备数据
x = torch.randn(batch_n, input_data)
y = torch.randn(batch_n, output_data)
#权 初始化
w1 = torch.randn(input_data, hidden_layer)
w2 = torch.randn(hidden_layer, output_data)
print(x.shape)
print(w1.shape)
print(w2.shape)
print(y.shape)

torch.Size([100, 1000])
torch.Size([1000, 100])
torch.Size([100, 10])
torch.Size([100, 10])


In [49]:
# 定后向传播的次数和梯度下降使用的学习 率。
epoch_n = 20
learning_rate = 1e-6

In [50]:
# 练
for epoch in range(epoch_n):
    #前向传播
    h1 = x.mm(w1) #[100,100]
    h1 = h1.clamp(min = 0) #使用clamp方法 行 剪 将小于 的值全  新赋值为0  就像加上了一个ReL
    y_pred = h1.mm(w2) #[100,10]
    # 算损失
    loss = (y_pred - y ).pow(2).sum() # 差值的 算使用了均方 差函数
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))
    #后向传播  算梯度使用的是每个 点的 式求导结果
    grad_y_pred = 2*(y_pred - y)
    grad_w2 = h1.t().mm(grad_y_pred)
    grad_h = grad_y_pred.clone()
    grad_h = grad_h.mm(w2.t())
    grad_h.clamp_(min=0)
    grad_w1 = x.t().mm(grad_h)
    #权 参数优化
    w1 -= learning_rate*grad_w1
    w2 -= learning_rate*grad_w2

Epoch:0, Loss:50054160.0000
Epoch:1, Loss:93008848.0000
Epoch:2, Loss:268537920.0000
Epoch:3, Loss:485145216.0000
Epoch:4, Loss:134842192.0000
Epoch:5, Loss:8219215.0000
Epoch:6, Loss:3935161.5000
Epoch:7, Loss:2775647.0000
Epoch:8, Loss:2329662.7500
Epoch:9, Loss:2077342.0000
Epoch:10, Loss:1891058.7500
Epoch:11, Loss:1736490.1250
Epoch:12, Loss:1602641.2500
Epoch:13, Loss:1484484.6250
Epoch:14, Loss:1379354.3750
Epoch:15, Loss:1285317.6250
Epoch:16, Loss:1201085.2500
Epoch:17, Loss:1125148.1250
Epoch:18, Loss:1056340.1250
Epoch:19, Loss:993898.6250


    通常来说我们是不用手写梯度的，上面这个作为人工智能专业的学生最好也掌握一下。
    接下来为大家介绍自动梯度

In [51]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

#权 初始化
w1 = Variable(torch.randn(input_data, hidden_layer), requires_grad = True)
w2 = Variable(torch.randn(hidden_layer, output_data), requires_grad = True)

In [52]:
# 定后向传播的次数和梯度下降使用的学习 率。
epoch_n = 20
learning_rate = 1e-6
# 练
for epoch in range(epoch_n):
    #前向传播
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    # 算损失
    loss = (y_pred - y ).pow(2).sum() # 差值的 算使用了均方 差函数
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))
    #后向传播 
    loss.backward()
    #权 参数更新
    w1.data -= learning_rate*w1.grad.data
    w2.data -= learning_rate*w2.grad.data
    w1.grad.data.zero_() #梯度值置 
    w2.grad.data.zero_() #梯度值置 

Epoch:0, Loss:39241920.0000
Epoch:1, Loss:54877476.0000
Epoch:2, Loss:159202256.0000
Epoch:3, Loss:420514112.0000
Epoch:4, Loss:331000384.0000
Epoch:5, Loss:3672128.7500
Epoch:6, Loss:2522745.2500
Epoch:7, Loss:1980010.5000
Epoch:8, Loss:1662198.7500
Epoch:9, Loss:1441561.0000
Epoch:10, Loss:1271295.0000
Epoch:11, Loss:1132102.3750
Epoch:12, Loss:1014682.3750
Epoch:13, Loss:914313.1875
Epoch:14, Loss:827432.8125
Epoch:15, Loss:751806.3750
Epoch:16, Loss:685570.8750
Epoch:17, Loss:627122.2500
Epoch:18, Loss:575456.8125
Epoch:19, Loss:529569.8125


In [53]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

In [54]:
class Model(torch.nn.Module):
    def _init_(self):
        super(Model, self)._init_()
    def forward(self, input, w1, w2):
        x = torch.mm(input, w1)
        x = torch.clamp(x, min = 0)
        x = torch.mm(x, w2)
        return x
    def backward(self):
        pass

In [55]:
model = Model()

In [56]:
#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)
#权 初始化
w1 = Variable(torch.randn(input_data, hidden_layer), requires_grad = True)
w2 = Variable(torch.randn(hidden_layer, output_data), requires_grad = True)
# 定后向传播的次数和梯度下降使用的学习 率。
epoch_n = 20
learning_rate = 1e-6
# 练
for epoch in range(epoch_n):
    #前向传播
    y_pred = model(x, w1, w2)
    # 算损失
    loss = (y_pred - y ).pow(2).sum() # 差值的 算使用了均方 差函数
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))
    #后向传播 
    loss.backward()
    #权 参数更新
    w1.data -= learning_rate*w1.grad.data
    w2.data -= learning_rate*w2.grad.data
   
    w1.grad.data.zero_() #梯度值置 
    w2.grad.data.zero_() #梯度值置 

Epoch:0, Loss:44922680.0000
Epoch:1, Loss:101032960.0000
Epoch:2, Loss:420813856.0000
Epoch:3, Loss:860729728.0000
Epoch:4, Loss:45626224.0000
Epoch:5, Loss:19612918.0000
Epoch:6, Loss:12024367.0000
Epoch:7, Loss:8339947.0000
Epoch:8, Loss:6195304.0000
Epoch:9, Loss:4809432.0000
Epoch:10, Loss:3851065.7500
Epoch:11, Loss:3156098.7500
Epoch:12, Loss:2633715.5000
Epoch:13, Loss:2230605.7500
Epoch:14, Loss:1912554.6250
Epoch:15, Loss:1657291.3750
Epoch:16, Loss:1449427.6250
Epoch:17, Loss:1278160.7500
Epoch:18, Loss:1135629.3750
Epoch:19, Loss:1015743.5625


### 通过上面这个过程我们就可以自己指定传播函数啦

# 模型搭建参数优化

In [57]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10
#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

In [58]:
models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)

In [59]:
hidden_layer = 100
input_data = 1000
output_data = 10
models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)
print(models)

Sequential(
  (0): Linear(in_features=1000, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)


In [60]:
hidden_layer = 100
input_data = 1000
output_data = 10
from collections import OrderedDict
models = torch.nn.Sequential(OrderedDict([
("Line1", torch.nn.Linear(input_data, hidden_layer)),
("Relu1", torch.nn.ReLU()),
("Line2", torch.nn.Linear(hidden_layer, output_data))])
)
print(models)

Sequential(
  (Line1): Linear(in_features=1000, out_features=100, bias=True)
  (Relu1): ReLU()
  (Line2): Linear(in_features=100, out_features=10, bias=True)
)


In [61]:
# 定后向传播的次数和梯度下降使用的学习 率。
epoch_n = 10000
learning_rate = 1e-4
#定义损失函数
loss_fn = torch.nn.MSELoss()

In [62]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
# x = Variable(torch.randn(100,100))
# y = Variable(torch.randn(100,100))
x = Variable(torch.FloatTensor([1,2,3]))
y = Variable(torch.FloatTensor([0,0,0]))
loss = loss_f(x, y)
print(loss)

tensor(4.6667)


In [63]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.L1Loss()
# x = Variable(torch.randn(100,100))
# y = Variable(torch.randn(100,100))
x = Variable(torch.FloatTensor([1,2,4]))
y = Variable(torch.FloatTensor([0,0,0]))
loss = loss_f(x, y)
print(loss)

tensor(2.3333)


In [64]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.CrossEntropyLoss()
x = Variable(torch.randn(3,5))
print(x)
y = Variable(torch.LongTensor(3).random_(5))
print(y)
# x = Variable(torch.FloatTensor([[1,2],[3,2]]))
# y = Variable(torch.LongTensor([1,0]))
loss = loss_f(x, y)
print(loss)

tensor([[-0.0129,  1.4924,  0.8029,  0.5426,  1.1644],
        [ 1.4464, -0.0689,  0.9223,  0.7673,  0.0966],
        [-0.4218, -0.5972, -0.4448, -0.1068, -0.5999]])
tensor([1, 3, 0])
tensor(1.4270)


In [65]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10
#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)
#定义模型
models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)
# 定后向传播的次数和梯度下降使用的学习 率。
epoch_n = 10000
learning_rate = 1e-4
#定义损失函数
loss_fn = torch.nn.MSELoss()
# 练
for epoch in range(epoch_n):
    #前向传播
    y_pred = models(x)
    
    # 算损失
    loss = loss_fn(y_pred, y)
    if epoch%1000 == 0:
        print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))
    models.zero_grad()
    #后向传播 
    loss.backward()
    #权 参数更新
    for param in models.parameters():
        param.data -= param.grad.data*learning_rate

Epoch:0, Loss:1.0405
Epoch:1000, Loss:0.9616
Epoch:2000, Loss:0.8929
Epoch:3000, Loss:0.8323
Epoch:4000, Loss:0.7778
Epoch:5000, Loss:0.7282
Epoch:6000, Loss:0.6829
Epoch:7000, Loss:0.6412
Epoch:8000, Loss:0.6024
Epoch:9000, Loss:0.5660


    和tensorflow基本一致的操作方式，问题不大。分析一下他的Module类就可以啦
    
    最后还可以使用torch.optim进一步简化

In [3]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10
#准备数据
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)
#定义模型
models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)
# 定后向传播的次数和梯度下降使用的学习 率。
epoch_n = 20
learning_rate = 1e-4
#定义损失函数
loss_fn = torch.nn.MSELoss()
#定义优化方法
optimzer = torch.optim.Adam(models.parameters(), lr = learning_rate)
# 练
for epoch in range(epoch_n):
    #前向传播
    y_pred = models(x)
    # 算损失
    loss = loss_fn(y_pred, y)
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss))
    optimzer.zero_grad()
    #后向传播 
    loss.backward()
    optimzer.step()

Epoch:0, Loss:1.0532
Epoch:1, Loss:1.0313
Epoch:2, Loss:1.0099
Epoch:3, Loss:0.9891
Epoch:4, Loss:0.9687
Epoch:5, Loss:0.9489
Epoch:6, Loss:0.9294
Epoch:7, Loss:0.9104
Epoch:8, Loss:0.8919
Epoch:9, Loss:0.8737
Epoch:10, Loss:0.8561
Epoch:11, Loss:0.8389
Epoch:12, Loss:0.8221
Epoch:13, Loss:0.8058
Epoch:14, Loss:0.7898
Epoch:15, Loss:0.7741
Epoch:16, Loss:0.7588
Epoch:17, Loss:0.7439
Epoch:18, Loss:0.7293
Epoch:19, Loss:0.7151


试试看增加一下markdown line并提交到github中